name: Validate frontend
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint-all:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4.0.0
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: pnpm
          cache-dependency-path: "frontend"
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint
      - run: pnpm run check
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4.0.0
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: pnpm
          cache-dependency-path: "frontend"
      - run: pnpm install --frozen-lockfile
      - run: pnpm run test
